using CommandLine;
using CommandLine.Text;
using System.Collections.Generic;
using System.Reflection;

namespace CopySharp.Console
{
  class CommandLineOptions
  {
    [OptionArray('s', "solutions", Required = false, HelpText = "Full path to the Visual Studio solution files (*.sln) you want to analyze with CopySharp. All C# projects within the solution will be analyzed.")]
    public string[] SolutionFilePaths { get; set; }

    [OptionArray('p', "projects", Required = false, HelpText = "Full path to the Visual Studio C# project files (*.csproj) you want to analyze with CopySharp.")]
    public string[] ProjectFilePaths { get; set; }

    [Option('o', "output", Required = true, HelpText = "Full path to the HTML output, which will contain the analysis report generated by CopySharp.")]
    public string OutputFilePath { get; set; }

    [HelpOption('h', "help", HelpText = "Displays this help.")]
    public string GetUsage()
    {
      var help = new HelpText
      {
        AdditionalNewLineAfterOption = true,
        AddDashesToOption = true,
        Copyright = "CopySharp version " + Assembly.GetExecutingAssembly().GetName().Version + "\nCreated by: Attila Zsigmond"
      };
      help.AddPreOptionsLine("Usage (example): CopySharp.exe -s \"C:\\fakepath\\Solution1.sln\" \"C:\\fakepath\\Solution2.sln\" \"C:\\folder one\\folder two\\Solution2.sln\" -o \"C:\\fakepath\\results.html\"");
      help.AddPreOptionsLine("Usage (example): CopySharp.exe -p \"C:\\fakepath\\demo\\MyProjectBusinessLogic.csproj\" -s \"C:\\fakepath\\Solution2.sln\" \"C:\\folder one\\folder two\\Solution2.sln\" -o \"C:\\fakepath\\results.html\"");
      help.AddOptions(this);
      return help;
    }
  }
}
